hydra:
  run:
    dir: .
  job:
    chdir: False
  output_subdir: null

defaults:
  - _self_
  - paths : default
  - params: base_model
  - run: base_run
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
